### ISSUE TITLE
Upgrade to Godot 4.2

### ISSUE THREAD

**Issue by ThinkCodePlay** [colinbellino/lemmings#1]
This Project looks Awsome. Any chance of upgrading this to work in 4.2?

**Comment by colinbellino** [comment]
I'm not sure what the point of an upgrade would be? 🤔

The game still works on the 3.x LTS and converting it would probably be a lot of work, so i don't see what the project would gain from doing this?

**Comment by ThinkCodePlay** [comment]
No problem. This is a fantastic resource for me. Thank You

**Comment by colinbellino** [comment]
Glad you like it, feel free to ask if you have questions :)
